version: '3'

services:
  cassandra:
    image: cassandra:3
    networks:
      - backoffice
    volumes:
      - kong-db-data:/var/lib/cassandra
      
  kong-migration:
    image: kong
    depends_on:
      - cassandra
    networks:
      - backoffice
    command: kong migrations up
    restart: on-failure
    environment:
      - KONG_DATABASE=cassandra
      - KONG_CASSANDRA_CONTACT_POINTS=cassandra
    
  kong:
    build: .
    depends_on:
      - cassandra
    networks:
      - frontoffice
      - backoffice
    restart: on-failure
    ports:
      - 8000:8000
      - 8001:8001
      - 8443:8443
      - 8444:8444
    environment:
      - KONG_DATABASE=cassandra
      - KONG_CASSANDRA_CONTACT_POINTS=cassandra
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_ADMIN_LISTEN_SSL=0.0.0.0:8444
      - KONG_PLUGINS=bundled,forward-proxy
      
networks:
  frontoffice:
  backoffice:
      
volumes:
  kong-db-data: